import type { Metadata } from "next";
import { Noto_Sans_JP, Outfit } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable} ${notoSansJP.variable} h-full`}>
      <body className="flex min-h-full flex-col antialiased">
        <Script
          src="https://use.typekit.net/ldm8iso.js"
          strategy="beforeInteractive"
        />
        <Script id="typekit-load" strategy="beforeInteractive">
          {`try{Typekit.load({ async: true });}catch(e){}`}
        </Script>
        {children}
      </body>
    </html>
  );
}
